

GET http://localhost:5000/ HTTP/1.1

###

POST http://localhost:5000/user/Create/ HTTP/1.1t
content-type: application/json

{
    "userName": "New",
    "password": "12345"
}

###
//Query all users
GET http://localhost:5000/user/ HTTP/1.1

###
//Query a user name
GET http://localhost:5000/user/find?name=sample HTTP/1.1t

###

DELETE http://localhost:5000/user/delete?name=sample HTTP/1.1t

###

PUT http://localhost:5000/user/update?name=sample HTTP/1.1t
content-type: application/json

{
    "email": "new@gmail.com"
}
###
//test login
post http://localhost:5000/user/login HTTP/1.1t
content-type: application/json

{
    "userName": "New",
    "password": "12345"
}

###